import TwoColumnLayout from '@/components/Templates/TwoColumnLayout';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "KeM's Toys",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <TwoColumnLayout>{children}</TwoColumnLayout>
      </body>
    </html>
  );
}
